# argocd-deploy-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastapi-app
  namespace: argocd
spec:
  destination:
    namespace: fastapi
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/purijs/mlops.git
    targetRevision: HEAD
    path: manifests/
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
